name: meili_flutter_ios
description: iOS implementation of the meili_flutter plugin
version: 0.2.0

homepage: https://github.com/meili-travel-tech/flutter_meili

environment:
    sdk: '>=3.4.0 <4.0.0'
    flutter: '>=1.20.0'

flutter:
    plugin:
        implements: meili_flutter
        platforms:
            ios:
                pluginClass: MeiliFlutterPlugin

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    plugin_platform_interface: ^2.1.8
    very_good_analysis: ^6.0.0
